//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAKI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Children = new HashSet<Department>();
            this.PersonHasJobInDeps = new HashSet<PersonHasJobInDep>();
        }
    
        public int DepartmentId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> Rules { get; set; }
    
        public virtual ICollection<Department> Children { get; set; }
        public virtual Department Parent { get; set; }
        public virtual ICollection<PersonHasJobInDep> PersonHasJobInDeps { get; set; }
    }
}
