//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAKI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.PersonHasJobInDeps = new HashSet<PersonHasJobInDep>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int PersonId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Adress { get; set; }
    
        public virtual ICollection<PersonHasJobInDep> PersonHasJobInDeps { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
