//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAKI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prize
    {
        public Prize()
        {
            this.UserBuysPrizes = new HashSet<UserBuysPrize>();
        }
    
        public int PrizeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Cost { get; set; }
        public int Limit { get; set; }
    
        public virtual ICollection<UserBuysPrize> UserBuysPrizes { get; set; }
    }
}
