//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAKI.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBuysPrize
    {
        public int UserId { get; set; }
        public int PrizeId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Prize Prize { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
