// <auto-generated />
namespace DAKI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class skills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(skills));
        
        string IMigrationMetadata.Id
        {
            get { return "201605292220001_skills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
