// <auto-generated />
namespace DAKI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class seedingstufff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedingstufff));
        
        string IMigrationMetadata.Id
        {
            get { return "201605300219161_seedingstufff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
