// <auto-generated />
namespace DAKI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Nigger : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nigger));
        
        string IMigrationMetadata.Id
        {
            get { return "201605281613288_Nigger"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
