//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAKI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DakiDbEntities : DbContext
    {
        public DakiDbEntities()
            : base("name=DakiDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Achievement> Achievements { get; set; }
        public DbSet<Badge> Badges { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<DepSupToDep> DepSupToDeps { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PersonHasJobInDep> PersonHasJobInDeps { get; set; }
        public DbSet<Prize> Prizes { get; set; }
        public DbSet<UserBuysPrize> UserBuysPrizes { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Mebership> webpages_Mebership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
